# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\field_depth.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(965, 594)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 561, 511))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(620, 20, 331, 511))
        self.widget.setObjectName("widget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.output_field_depth = QtWidgets.QRadioButton(self.widget)
        self.output_field_depth.setChecked(True)
        self.output_field_depth.setObjectName("output_field_depth")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.output_field_depth)
        self.gridLayout_4.addWidget(self.output_field_depth, 0, 1, 1, 1)
        self.output_image_distance = QtWidgets.QRadioButton(self.widget)
        self.output_image_distance.setObjectName("output_image_distance")
        self.buttonGroup.addButton(self.output_image_distance)
        self.gridLayout_4.addWidget(self.output_image_distance, 0, 2, 1, 1)
        self.output_params = QtWidgets.QRadioButton(self.widget)
        self.output_params.setChecked(False)
        self.output_params.setObjectName("output_params")
        self.buttonGroup.addButton(self.output_params)
        self.gridLayout_4.addWidget(self.output_params, 0, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_4)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.input_focus_length = QtWidgets.QRadioButton(self.widget)
        self.input_focus_length.setObjectName("input_focus_length")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.input_focus_length)
        self.gridLayout_5.addWidget(self.input_focus_length, 0, 1, 1, 1)
        self.input_apeture = QtWidgets.QRadioButton(self.widget)
        self.input_apeture.setObjectName("input_apeture")
        self.buttonGroup_2.addButton(self.input_apeture)
        self.gridLayout_5.addWidget(self.input_apeture, 0, 2, 1, 1)
        self.input_distance = QtWidgets.QRadioButton(self.widget)
        self.input_distance.setChecked(True)
        self.input_distance.setObjectName("input_distance")
        self.buttonGroup_2.addButton(self.input_distance)
        self.gridLayout_5.addWidget(self.input_distance, 0, 3, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.verticalLayout_10.addLayout(self.verticalLayout_7)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_6.addWidget(self.label_11)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.basic_setting = QtWidgets.QFormLayout()
        self.basic_setting.setObjectName("basic_setting")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.basic_setting.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.basic_setting.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.aperture = QtWidgets.QDoubleSpinBox(self.widget)
        self.aperture.setSingleStep(0.1)
        self.aperture.setProperty("value", 1.4)
        self.aperture.setObjectName("aperture")
        self.basic_setting.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.aperture)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.basic_setting.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.focus_distance = QtWidgets.QDoubleSpinBox(self.widget)
        self.focus_distance.setBaseSize(QtCore.QSize(2, 2))
        self.focus_distance.setProperty("value", 2.0)
        self.focus_distance.setObjectName("focus_distance")
        self.basic_setting.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.focus_distance)
        self.focus_length = QtWidgets.QDoubleSpinBox(self.widget)
        self.focus_length.setMaximum(200.0)
        self.focus_length.setProperty("value", 50.0)
        self.focus_length.setObjectName("focus_length")
        self.basic_setting.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.focus_length)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.basic_setting.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.sensor_size_list = QtWidgets.QComboBox(self.widget)
        self.sensor_size_list.setObjectName("sensor_size_list")
        self.basic_setting.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sensor_size_list)
        self.horizontalLayout_3.addLayout(self.basic_setting)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_9.addLayout(self.verticalLayout_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem2)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.sensor_size = QtWidgets.QDoubleSpinBox(self.widget)
        self.sensor_size.setMaximum(100.0)
        self.sensor_size.setSingleStep(0.005)
        self.sensor_size.setProperty("value", 43.27)
        self.sensor_size.setObjectName("sensor_size")
        self.horizontalLayout.addWidget(self.sensor_size)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.confusion_circle_diam_slide = QtWidgets.QSlider(self.widget)
        self.confusion_circle_diam_slide.setProperty("value", 50)
        self.confusion_circle_diam_slide.setOrientation(QtCore.Qt.Horizontal)
        self.confusion_circle_diam_slide.setObjectName("confusion_circle_diam_slide")
        self.horizontalLayout_2.addWidget(self.confusion_circle_diam_slide)
        self.confusion_circle_diam = QtWidgets.QDoubleSpinBox(self.widget)
        self.confusion_circle_diam.setDecimals(3)
        self.confusion_circle_diam.setMaximum(1.0)
        self.confusion_circle_diam.setSingleStep(0.005)
        self.confusion_circle_diam.setProperty("value", 0.04)
        self.confusion_circle_diam.setObjectName("confusion_circle_diam")
        self.horizontalLayout_2.addWidget(self.confusion_circle_diam)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.focus_min_range = QtWidgets.QDoubleSpinBox(self.widget)
        self.focus_min_range.setObjectName("focus_min_range")
        self.horizontalLayout_4.addWidget(self.focus_min_range)
        self.focus_max_range = QtWidgets.QDoubleSpinBox(self.widget)
        self.focus_max_range.setObjectName("focus_max_range")
        self.horizontalLayout_4.addWidget(self.focus_max_range)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.apeture_min_range = QtWidgets.QDoubleSpinBox(self.widget)
        self.apeture_min_range.setObjectName("apeture_min_range")
        self.horizontalLayout_5.addWidget(self.apeture_min_range)
        self.apeture_max_range = QtWidgets.QDoubleSpinBox(self.widget)
        self.apeture_max_range.setObjectName("apeture_max_range")
        self.horizontalLayout_5.addWidget(self.apeture_max_range)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.distance_min_range = QtWidgets.QDoubleSpinBox(self.widget)
        self.distance_min_range.setObjectName("distance_min_range")
        self.horizontalLayout_6.addWidget(self.distance_min_range)
        self.distance_max_range = QtWidgets.QDoubleSpinBox(self.widget)
        self.distance_max_range.setObjectName("distance_max_range")
        self.horizontalLayout_6.addWidget(self.distance_max_range)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_8.addLayout(self.verticalLayout_2)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_8.addWidget(self.pushButton)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_10.addLayout(self.verticalLayout_9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 965, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "景深计算器"))
        self.label_10.setText(_translate("MainWindow", "变量设置"))
        self.label_5.setText(_translate("MainWindow", "图像输出"))
        self.output_field_depth.setText(_translate("MainWindow", "景深"))
        self.output_image_distance.setText(_translate("MainWindow", "像距"))
        self.output_params.setText(_translate("MainWindow", "参数"))
        self.label_6.setText(_translate("MainWindow", "变量"))
        self.input_focus_length.setText(_translate("MainWindow", "焦距"))
        self.input_apeture.setText(_translate("MainWindow", "光圈"))
        self.input_distance.setText(_translate("MainWindow", "物距"))
        self.label_11.setText(_translate("MainWindow", "基础设置"))
        self.label_4.setText(_translate("MainWindow", "焦距(mm)"))
        self.label.setText(_translate("MainWindow", "光圈(F)"))
        self.label_2.setText(_translate("MainWindow", "物体距离(m)"))
        self.label_8.setText(_translate("MainWindow", "sensor尺寸(英寸)"))
        self.label_9.setText(_translate("MainWindow", "高级设置"))
        self.label_3.setText(_translate("MainWindow", "sensor尺寸(mm)"))
        self.label_7.setText(_translate("MainWindow", "弥散圈直径(mm)"))
        self.label_12.setText(_translate("MainWindow", "焦距范围(mm)"))
        self.label_13.setText(_translate("MainWindow", "光圈范围(F)"))
        self.label_14.setText(_translate("MainWindow", "对焦范围(m)"))
        self.pushButton.setText(_translate("MainWindow", "确认"))
