# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\field_depth.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(851, 543)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 481, 461))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(520, 20, 311, 461))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 103, 76))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 10, 83, 16))
        self.radioButton_2.setAcceptDrops(False)
        self.radioButton_2.setChecked(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 30, 83, 16))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 50, 83, 16))
        self.radioButton_3.setObjectName("radioButton_3")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_4)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 100, 198, 100))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.aperture = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.aperture.setSingleStep(0.1)
        self.aperture.setProperty("value", 1.4)
        self.aperture.setObjectName("aperture")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.aperture)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.focus_distance = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.focus_distance.setBaseSize(QtCore.QSize(2, 2))
        self.focus_distance.setProperty("value", 2.0)
        self.focus_distance.setObjectName("focus_distance")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.focus_distance)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.sensor_size = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.sensor_size.setMaximum(100.0)
        self.sensor_size.setSingleStep(0.005)
        self.sensor_size.setProperty("value", 35.0)
        self.sensor_size.setObjectName("sensor_size")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.sensor_size)
        self.focus_length = QtWidgets.QDoubleSpinBox(self.formLayoutWidget)
        self.focus_length.setMaximum(200.0)
        self.focus_length.setProperty("value", 50.0)
        self.focus_length.setObjectName("focus_length")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.focus_length)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        self.scrollArea.setGeometry(QtCore.QRect(20, 20, 201, 161))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 199, 159))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 201, 31))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.confusion_circle_diam = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_2)
        self.confusion_circle_diam.setDecimals(3)
        self.confusion_circle_diam.setMaximum(1.0)
        self.confusion_circle_diam.setSingleStep(0.005)
        self.confusion_circle_diam.setProperty("value", 0.035)
        self.confusion_circle_diam.setObjectName("confusion_circle_diam")
        self.gridLayout_2.addWidget(self.confusion_circle_diam, 0, 1, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 851, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "景深计算器"))
        self.groupBox_4.setTitle(_translate("MainWindow", "基础设置"))
        self.radioButton_2.setText(_translate("MainWindow", "景深物距图"))
        self.radioButton.setText(_translate("MainWindow", "景深焦距图"))
        self.radioButton_3.setText(_translate("MainWindow", "景深光圈图"))
        self.label_4.setText(_translate("MainWindow", "焦距(mm)"))
        self.label.setText(_translate("MainWindow", "光圈(F)"))
        self.label_2.setText(_translate("MainWindow", "物体距离(m)"))
        self.label_3.setText(_translate("MainWindow", "sensor尺寸(mm)"))
        self.groupBox_2.setTitle(_translate("MainWindow", "高级设置"))
        self.label_7.setText(_translate("MainWindow", "弥散圈直径(mm)"))
        self.pushButton.setText(_translate("MainWindow", "确认"))
